apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx
    namespace: api
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - name: http
          containerPort: 80
